# -*- coding: utf-8 -*-
"""xee_service.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1__MmZKLTfOB5hZ9Tv4SUCk7ZQCjB-BWz
"""

import ee
import xee
import xarray as xr

# Path to your service account JSON key file
SERVICE_ACCOUNT_FILE = '/content/hm-30x30-9cf14c6efc4c.json'

# Authenticate and initialize with the service account
ee_creds = ee.ServiceAccountCredentials('', SERVICE_ACCOUNT_FILE)
ee.Initialize(ee_creds)

# Verify the initialization
testim = ee.Image("USGS/SRTMGL1_003")

# Open the Earth Engine image as an xarray Dataset using the 'ee' engine
ds = xr.open_dataset(testim, engine='ee')

# Display the dataset
ds